data:
  hrmaps_dir: "/gpfs02/work/akira.tokiwa/gpgpu/FastPM/healpix/nc256/"
  lrmaps_dir: "/gpfs02/work/akira.tokiwa/gpgpu/FastPM/healpix/nc128/"
  nside: 512
  n_maps: 100
  rate_train: 0.8
  order: 2
  issplit: True

train:
  num_epochs: 500
  batch_size: 2
  learning_rate: 1e-5

model:
  inner_channels: 64
  mults: [1, 2, 4, 8]